Repository openshift-knative/eventing, pull requests merged in 2023-11, with the labels that each got.

#410 Align names for mtbroker with upstream
  openshift/generate.sh
Labels: approved, lgtm

#399 [release-v1.12] Patch for chmod on codegen files
  openshift/patches/027-chmod-codegen.patch
  openshift/release/generate-release.sh
  vendor/knative.dev/hack/codegen-library.sh
Labels: lgtm

#418 [release-v1.11] Gather traces for TestChannelDeadLetterSinkExtensions
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
Labels: approved, lgtm

#400 [release-v1.11] Add encryption and auth tests
  Makefile
  openshift/e2e-common.sh
  openshift/e2e-encryption-auth-tests.sh
  openshift/knative-eventing-encryption-auth.yaml
Labels: approved, lgtm

#425 skipping make command for P/Z.
  openshift/e2e-common.sh
Labels: approved, lgtm, needs-ok-to-test

#434 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#442 [release-v1.12] Run `make generate-release`
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/source-image/Dockerfile
Labels: lgtm

#445 [release-v1.11] Run `make generate-release`
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
Labels: approved, lgtm

#446 [release-v1.11] fix the type coercion of triggers in broker filter
  pkg/broker/filter/filter_handler.go
Labels: approved, lgtm
