Repository openshift-knative/eventing, pull requests merged in 2023-12, with the labels that each got.

#441 CM Bundle injection for api server source
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/resources/cabundle_configmap.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, lgtm

#451 Fix config resolve script after image rename
  openshift/release/resolve.sh
Labels: approved, lgtm

#426 [release-v1.11] Allow configuring whether to allow cross namespaces Brokers configuration references (#7455)
  pkg/apis/config/defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/broker_validation.go
  pkg/apis/eventing/v1/broker_validation_test.go
Labels: approved, lgtm

#455 Backporting the 'ApiServerSource CM create and mount' patch to release-next (main)
  openshift/patches/023-configmap-trusted-cabundle_apiserver_source.patch
Labels: approved, lgtm

#452 Remove deprecated image replacements
  openshift/release/resolve.sh
Labels: approved, lgtm

#429 Upgrade tests account for last event being interrupted (#7447)
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/types.go
  test/upgrade/prober/wathola/sender/services.go
Labels: approved, lgtm

#463 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#465 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#449 Running gofmt...
  test/e2e/broker_defaults_webhook_test.go
  test/rekt/sink_binding_test.go
Labels: approved, lgtm

#472 Use correct OWNER_ALIASES when cutting release branch
  openshift/release/create-release-branch.sh
Labels: approved
