Repository openshift-knative/eventing, pull requests merged in 2024-10, with the labels that each got.

#891 [release-v1.14] workaround DeepDerivative CreationTimestamp comparison
  pkg/auth/serviceaccount.go
Labels: approved, lgtm

#884 [release-v1.15] Add Istio inject label (#8205)
  config/post-install/storage-version-migrator.yaml
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  test/config/monitoring/monitoring.yaml
  test/upgrade/prober/forwarder.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
  test/upgrade/prober/verify.go
Labels: approved

#898 [release-v1.15] Bump to latest upstream reconciler-test
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/cronjob/cronjob.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/job/job.go
  vendor/knative.dev/reconciler-test/pkg/resources/pod/pod.go
  vendor/modules.txt
Labels: approved, lgtm

#900 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#913 [release-v1.16] Install tzdata
  openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/appender/Dockerfile
  openshift/ci-operator/knative-images/channel_controller/Dockerfile
  openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/heartbeats_receiver/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/knative-images/jobsink/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/mqttsource/Dockerfile
  openshift/ci-operator/knative-images/mtchannel_broker/Dockerfile
  openshift/ci-operator/knative-images/mtping/Dockerfile
  openshift/ci-operator/knative-images/pong/Dockerfile
  openshift/ci-operator/knative-images/schema/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-images/websocketsource/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/generate.sh
Labels: approved, lgtm
