Repository openshift-knative/eventing, pull requests merged in 2024-02, with the labels that each got.

#515 [release-v1.11] Don't use async handler (#7415)
  pkg/channel/fanout/fanout_event_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  test/rekt/broker_test.go
Labels: approved, lgtm

#516 [release-v1.12] Don't use async handler (#7415)
  pkg/channel/fanout/fanout_event_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  test/rekt/broker_test.go
Labels: approved, lgtm

#521 [release-v1.11] Remove cert-manager setup, use the one in SO
  openshift/e2e-common.sh
Labels: approved

#531 [release-v1.11] update reconciler-test to current release-1.11
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: approved, lgtm

#536 Fix authentication feature flag name in configmap
  openshift/knative-eventing-encryption-auth.yaml
Labels: approved, lgtm

#532 [release-v1.11] backport receiver trace step annotation
  test/upgrade/prober/wathola/receiver/services.go
Labels: approved, lgtm

#530 Wait for events with poll interval after finished event received (#7668)
  test/upgrade/prober/wathola/config/defaults.go
  test/upgrade/prober/wathola/config/defaults_test.go
  test/upgrade/prober/wathola/config/structure.go
  test/upgrade/prober/wathola/event/services.go
Labels: approved, lgtm

#535 [release-1.13] Move OIDC tests to test/rekt
  test/auth/main_test.go
  test/auth/oidc_test.go
  test/config-authentication-oidc/features.yaml
  test/e2e-rekt-tests.sh
  test/rekt/apiserversource_test.go
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/container_source_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/apiserversource/oidc_feature.go
  test/rekt/features/broker/oidc_feature.go
  test/rekt/features/channel/oidc_feature.go
  test/rekt/features/containersource/oidc_feature.go
  test/rekt/features/oidc/addressable_oidc_conformance.go
  test/rekt/features/parallel/oidc_feature.go
  test/rekt/features/pingsource/oidc_feature.go
  test/rekt/features/sequence/oidc_feature.go
  test/rekt/parallel_test.go
  test/rekt/pingsource_test.go
  test/rekt/sequence_test.go
Labels: approved, lgtm

#541 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#547 [release-v1.11] Remove assumption on default namespace for EventType reference
  go.sum
  openshift/ci-operator/source-image/Dockerfile
  openshift/release/artifacts/eventing-core.yaml
  openshift/release/artifacts/eventing-crds.yaml
  pkg/apis/eventing/v1beta1/eventtype_defaults.go
  pkg/apis/eventing/v1beta2/eventtype_defaults.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/source/duck/duck_test.go
Labels: approved, lgtm
