Repository openshift-knative/eventing, pull requests merged in 2024-11, with the labels that each got.

#949 [release-v1.15] Add observedGeneration in JobSink OpenAPI schema
  config/core/resources/jobsink.yaml
  openshift/release/artifacts/eventing-core.yaml
  openshift/release/artifacts/eventing-crds.yaml
  pkg/reconciler/jobsink/jobsink_test.go
Labels: approved, lgtm

#952 [release-v1.15] Use GetServiceHostname when passing URL to JobSink (#8303)
  test/rekt/features/jobsink/jobsink.go
Labels: approved, lgtm

#944 [release-v1.14] Install tzdata
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/appender/Dockerfile
  openshift/ci-operator/knative-images/channel_controller/Dockerfile
  openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/heartbeats_receiver/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/mtchannel_broker/Dockerfile
  openshift/ci-operator/knative-images/mtping/Dockerfile
  openshift/ci-operator/knative-images/pong/Dockerfile
  openshift/ci-operator/knative-images/schema/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-images/websocketsource/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/performance/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/generate.sh
Labels: approved

#962 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#963 [release-v1.15] Run `make generate-release`
  openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/appender/Dockerfile
  openshift/ci-operator/knative-images/channel_controller/Dockerfile
  openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/heartbeats_receiver/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/knative-images/jobsink/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/mqttsource/Dockerfile
  openshift/ci-operator/knative-images/mtchannel_broker/Dockerfile
  openshift/ci-operator/knative-images/mtping/Dockerfile
  openshift/ci-operator/knative-images/pong/Dockerfile
  openshift/ci-operator/knative-images/schema/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-images/websocketsource/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Labels: approved, lgtm

#965 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
Labels: approved, lgtm
