Repository openshift-knative/eventing, pull requests merged in 2024-06, with the labels that each got.

#617 allow skipping generate-release
  openshift/e2e-common.sh
Labels: approved, lgtm

#622 fix: receive adapter seccomp patch works with the bundle injection patch removed
  openshift/patches/remove_seccompProfile.patch
Labels: approved, lgtm

#624 Add JobSink Certificate to TLS artifact
  openshift/release/generate-release.sh
Labels: approved, lgtm

#625 Change core TLS directory
  openshift/release/generate-release.sh
Labels: approved, lgtm

#627 [release-v1.14] Fix possible nil pointer dereference in event-dispatcher
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, lgtm

#626 [release-v1.12] Fix possible nil pointer dereference in event-dispatcher
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, lgtm

#630 [release-v1.14] Propagate read error correctly in event-dispatcher
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, lgtm

#629 [release-v1.12] Propagate read error correctly in event-dispatcher
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, lgtm

#631 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-apiserver-receive-adapter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-appender.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-filter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-ingress.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-jobsink.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtchannel-broker.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtping.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-pong.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-schema.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-webhook.yaml
  .konflux/applications/serverless-operator-release-next/serverless-operator-release-next.yaml
  .tekton/docker-build-oci-ta.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-pull-request.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-push.yaml
  .tekton/knative-eventing-appender-pull-request.yaml
  .tekton/knative-eventing-appender-push.yaml
  .tekton/knative-eventing-channel-controller-pull-request.yaml
  .tekton/knative-eventing-channel-controller-push.yaml
  .tekton/knative-eventing-channel-dispatcher-pull-request.yaml
  .tekton/knative-eventing-channel-dispatcher-push.yaml
  .tekton/knative-eventing-controller-pull-request.yaml
  .tekton/knative-eventing-controller-push.yaml
  .tekton/knative-eventing-event-display-pull-request.yaml
  .tekton/knative-eventing-event-display-push.yaml
  .tekton/knative-eventing-filter-pull-request.yaml
  .tekton/knative-eventing-filter-push.yaml
  .tekton/knative-eventing-heartbeats-pull-request.yaml
  .tekton/knative-eventing-heartbeats-push.yaml
  .tekton/knative-eventing-heartbeats-receiver-pull-request.yaml
  .tekton/knative-eventing-heartbeats-receiver-push.yaml
  .tekton/knative-eventing-ingress-pull-request.yaml
  .tekton/knative-eventing-ingress-push.yaml
  .tekton/knative-eventing-jobsink-pull-request.yaml
  .tekton/knative-eventing-jobsink-push.yaml
  .tekton/knative-eventing-migrate-pull-request.yaml
  .tekton/knative-eventing-migrate-push.yaml
  .tekton/knative-eventing-mtchannel-broker-pull-request.yaml
  .tekton/knative-eventing-mtchannel-broker-push.yaml
  .tekton/knative-eventing-mtping-pull-request.yaml
  .tekton/knative-eventing-mtping-push.yaml
  .tekton/knative-eventing-pong-pull-request.yaml
  .tekton/knative-eventing-pong-push.yaml
  .tekton/knative-eventing-schema-pull-request.yaml
  .tekton/knative-eventing-schema-push.yaml
  .tekton/knative-eventing-webhook-pull-request.yaml
  .tekton/knative-eventing-webhook-push.yaml
Labels: approved, lgtm

#632 [main] Checkout .konflux and .tekton for release-next sync
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#645 Switch to go install to install hack/generate
  openshift/generate.sh
Labels: approved, lgtm

#647 Enable debug logging in generate.sh
  openshift/generate.sh
Labels: approved

#648 Build generate binary directly
  openshift/generate.sh
Labels: approved, lgtm

#654 Clone hack repo to install generate
  openshift/generate.sh
Labels: approved, lgtm

#655 Cleanup after hack repo clone
  openshift/generate.sh
Labels: approved, lgtm

#656 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-apiserver-receive-adapter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-appender.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-filter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-ingress.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-jobsink.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtchannel-broker.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtping.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-pong.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-schema.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-webhook.yaml
Labels: approved, lgtm

#657 Use OCP 4.17 based image in generate to support Go 1.22
  openshift/generate.sh
Labels: approved, lgtm

#676 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-apiserver-receive-adapter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-appender.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-filter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-ingress.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-jobsink.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtchannel-broker.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtping.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-pong.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-schema.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-webhook.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-pull-request.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-push.yaml
  .tekton/knative-eventing-appender-pull-request.yaml
  .tekton/knative-eventing-appender-push.yaml
  .tekton/knative-eventing-channel-controller-pull-request.yaml
  .tekton/knative-eventing-channel-controller-push.yaml
  .tekton/knative-eventing-channel-dispatcher-pull-request.yaml
  .tekton/knative-eventing-channel-dispatcher-push.yaml
  .tekton/knative-eventing-controller-pull-request.yaml
  .tekton/knative-eventing-controller-push.yaml
  .tekton/knative-eventing-event-display-pull-request.yaml
  .tekton/knative-eventing-event-display-push.yaml
  .tekton/knative-eventing-filter-pull-request.yaml
  .tekton/knative-eventing-filter-push.yaml
  .tekton/knative-eventing-heartbeats-pull-request.yaml
  .tekton/knative-eventing-heartbeats-push.yaml
  .tekton/knative-eventing-heartbeats-receiver-pull-request.yaml
  .tekton/knative-eventing-heartbeats-receiver-push.yaml
  .tekton/knative-eventing-ingress-pull-request.yaml
  .tekton/knative-eventing-ingress-push.yaml
  .tekton/knative-eventing-jobsink-pull-request.yaml
  .tekton/knative-eventing-jobsink-push.yaml
  .tekton/knative-eventing-migrate-pull-request.yaml
  .tekton/knative-eventing-migrate-push.yaml
  .tekton/knative-eventing-mtchannel-broker-pull-request.yaml
  .tekton/knative-eventing-mtchannel-broker-push.yaml
  .tekton/knative-eventing-mtping-pull-request.yaml
  .tekton/knative-eventing-mtping-push.yaml
  .tekton/knative-eventing-pong-pull-request.yaml
  .tekton/knative-eventing-pong-push.yaml
  .tekton/knative-eventing-schema-pull-request.yaml
  .tekton/knative-eventing-schema-push.yaml
  .tekton/knative-eventing-webhook-pull-request.yaml
  .tekton/knative-eventing-webhook-push.yaml
Labels: do-not-merge/hold

#677 [main] Add Konflux configurations
  .tekton/knative-eventing-apiserver-receive-adapter-pull-request.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-push.yaml
  .tekton/knative-eventing-appender-pull-request.yaml
  .tekton/knative-eventing-appender-push.yaml
  .tekton/knative-eventing-channel-controller-pull-request.yaml
  .tekton/knative-eventing-channel-controller-push.yaml
  .tekton/knative-eventing-channel-dispatcher-pull-request.yaml
  .tekton/knative-eventing-channel-dispatcher-push.yaml
  .tekton/knative-eventing-controller-pull-request.yaml
  .tekton/knative-eventing-controller-push.yaml
  .tekton/knative-eventing-event-display-pull-request.yaml
  .tekton/knative-eventing-event-display-push.yaml
  .tekton/knative-eventing-filter-pull-request.yaml
  .tekton/knative-eventing-filter-push.yaml
  .tekton/knative-eventing-heartbeats-pull-request.yaml
  .tekton/knative-eventing-heartbeats-push.yaml
  .tekton/knative-eventing-heartbeats-receiver-pull-request.yaml
  .tekton/knative-eventing-heartbeats-receiver-push.yaml
  .tekton/knative-eventing-ingress-pull-request.yaml
  .tekton/knative-eventing-ingress-push.yaml
  .tekton/knative-eventing-jobsink-pull-request.yaml
  .tekton/knative-eventing-jobsink-push.yaml
  .tekton/knative-eventing-migrate-pull-request.yaml
  .tekton/knative-eventing-migrate-push.yaml
  .tekton/knative-eventing-mtchannel-broker-pull-request.yaml
  .tekton/knative-eventing-mtchannel-broker-push.yaml
  .tekton/knative-eventing-mtping-pull-request.yaml
  .tekton/knative-eventing-mtping-push.yaml
  .tekton/knative-eventing-pong-pull-request.yaml
  .tekton/knative-eventing-pong-push.yaml
  .tekton/knative-eventing-schema-pull-request.yaml
  .tekton/knative-eventing-schema-push.yaml
  .tekton/knative-eventing-webhook-pull-request.yaml
  .tekton/knative-eventing-webhook-push.yaml
Labels: approved, lgtm

#680 [main] Add Konflux configurations
  .tekton/knative-eventing-apiserver-receive-adapter-pull-request.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-push.yaml
  .tekton/knative-eventing-appender-pull-request.yaml
  .tekton/knative-eventing-appender-push.yaml
  .tekton/knative-eventing-channel-controller-pull-request.yaml
  .tekton/knative-eventing-channel-controller-push.yaml
  .tekton/knative-eventing-channel-dispatcher-pull-request.yaml
  .tekton/knative-eventing-channel-dispatcher-push.yaml
  .tekton/knative-eventing-controller-pull-request.yaml
  .tekton/knative-eventing-controller-push.yaml
  .tekton/knative-eventing-event-display-pull-request.yaml
  .tekton/knative-eventing-event-display-push.yaml
  .tekton/knative-eventing-filter-pull-request.yaml
  .tekton/knative-eventing-filter-push.yaml
  .tekton/knative-eventing-heartbeats-pull-request.yaml
  .tekton/knative-eventing-heartbeats-push.yaml
  .tekton/knative-eventing-heartbeats-receiver-pull-request.yaml
  .tekton/knative-eventing-heartbeats-receiver-push.yaml
  .tekton/knative-eventing-ingress-pull-request.yaml
  .tekton/knative-eventing-ingress-push.yaml
  .tekton/knative-eventing-jobsink-pull-request.yaml
  .tekton/knative-eventing-jobsink-push.yaml
  .tekton/knative-eventing-migrate-pull-request.yaml
  .tekton/knative-eventing-migrate-push.yaml
  .tekton/knative-eventing-mtchannel-broker-pull-request.yaml
  .tekton/knative-eventing-mtchannel-broker-push.yaml
  .tekton/knative-eventing-mtping-pull-request.yaml
  .tekton/knative-eventing-mtping-push.yaml
  .tekton/knative-eventing-pong-pull-request.yaml
  .tekton/knative-eventing-pong-push.yaml
  .tekton/knative-eventing-schema-pull-request.yaml
  .tekton/knative-eventing-schema-push.yaml
  .tekton/knative-eventing-webhook-pull-request.yaml
  .tekton/knative-eventing-webhook-push.yaml
Labels: approved, lgtm

#652 Workaround for OCPBUGS-35731 Repeat deleting service accounts
  openshift/patches/027-rekt-serviceaccounts-delete.patch
  openshift/release/generate-release.sh
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
Labels: approved, lgtm
