Repository openshift-knative/eventing, pull requests merged in 2024-08, with the labels that each got.

#702 [main] Add Konflux configurations
  .tekton/docker-build-oci-ta.yaml
Labels: approved, lgtm

#704 try skipping header
  openshift/e2e-common.sh
Labels: approved, lgtm

#705 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-apiserver-receive-adapter.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-appender.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-channel-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-channel-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-filter.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-heartbeats-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-ingress.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-jobsink.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-mtchannel-broker.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-mtping.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-pong.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-schema.yaml
  .konflux/applications/serverless-operator-release-next/components/imagerepositories/openshift-knative-eventing-release-next-knative-eventing-webhook.yaml
Labels: approved, lgtm

#759 [release-v1.14] Run `make generate-release`
  openshift/release/artifacts/eventing-core.yaml
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
  vendor/knative.dev/reconciler-test/pkg/manifest/testdata/100-ns.yaml
  vendor/knative.dev/reconciler-test/pkg/manifest/testdata/101-pod.yaml
Labels: approved, lgtm

#761 [main] Add Konflux configurations
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-apiserver-receive-adapter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-appender.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-channel-dispatcher.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-controller.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-event-display.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-filter.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats-receiver.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-heartbeats.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-ingress.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-jobsink.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-migrate.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtchannel-broker.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-mtping.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-pong.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-schema.yaml
  .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-release-next-knative-eventing-webhook.yaml
Labels: approved, lgtm

#764 [main] Add Konflux configurations
  .tekton/docker-build.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-release-next-pull-request.yaml
  .tekton/knative-eventing-apiserver-receive-adapter-release-next-push.yaml
  .tekton/knative-eventing-appender-release-next-pull-request.yaml
  .tekton/knative-eventing-appender-release-next-push.yaml
  .tekton/knative-eventing-channel-controller-release-next-pull-request.yaml
  .tekton/knative-eventing-channel-controller-release-next-push.yaml
  .tekton/knative-eventing-channel-dispatcher-release-next-pull-request.yaml
  .tekton/knative-eventing-channel-dispatcher-release-next-push.yaml
  .tekton/knative-eventing-controller-release-next-pull-request.yaml
  .tekton/knative-eventing-controller-release-next-push.yaml
  .tekton/knative-eventing-event-display-release-next-pull-request.yaml
  .tekton/knative-eventing-event-display-release-next-push.yaml
  .tekton/knative-eventing-filter-release-next-pull-request.yaml
  .tekton/knative-eventing-filter-release-next-push.yaml
  .tekton/knative-eventing-heartbeats-receiver-release-next-pull-request.yaml
  .tekton/knative-eventing-heartbeats-receiver-release-next-push.yaml
  .tekton/knative-eventing-heartbeats-release-next-pull-request.yaml
  .tekton/knative-eventing-heartbeats-release-next-push.yaml
  .tekton/knative-eventing-ingress-release-next-pull-request.yaml
  .tekton/knative-eventing-ingress-release-next-push.yaml
  .tekton/knative-eventing-jobsink-release-next-pull-request.yaml
  .tekton/knative-eventing-jobsink-release-next-push.yaml
  .tekton/knative-eventing-migrate-release-next-pull-request.yaml
  .tekton/knative-eventing-migrate-release-next-push.yaml
  .tekton/knative-eventing-mtchannel-broker-release-next-pull-request.yaml
  .tekton/knative-eventing-mtchannel-broker-release-next-push.yaml
  .tekton/knative-eventing-mtping-release-next-pull-request.yaml
  .tekton/knative-eventing-mtping-release-next-push.yaml
  .tekton/knative-eventing-pong-release-next-pull-request.yaml
  .tekton/knative-eventing-pong-release-next-push.yaml
  .tekton/knative-eventing-schema-release-next-pull-request.yaml
  .tekton/knative-eventing-schema-release-next-push.yaml
  .tekton/knative-eventing-webhook-release-next-pull-request.yaml
  .tekton/knative-eventing-webhook-release-next-push.yaml
Labels: approved, lgtm

#623 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream

#768 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/knative-eventing-controller-pull-request.yaml
  .tekton/knative-eventing-controller-push.yaml
Labels: approved, lgtm, ok-to-test

#775 [release-v1.14] EventType tests verify the type under spec.reference
  test/experimental/features/eventtype_autocreate/features.go
  test/rekt/features/pingsource/features.go
Labels: approved, lgtm
