Repository openshift-knative/eventing, pull requests merged in 2025-02, with the labels that each got.

#1048 [release-v1.17] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: needs-ok-to-test

#1046 [release-v1.16] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: needs-ok-to-test

#1049 [release-v1.17] Add `sinks.knative.dev` to namespaced ClusterRole (#8433)
  config/core/roles/clusterrole-namespaced.yaml
  openshift/release/artifacts/eventing-core.yaml
Labels: approved, lgtm

#1044 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1058 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1060 Run AuthZ tests too as part of auth test suite
  openshift/e2e-common.sh
Labels: approved, lgtm

#1059 [release-v1.16] Add health check config and clean up duplicated code (#8308)
  cmd/controller/main.go
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  openshift/release/artifacts/eventing-core.yaml
  openshift/release/artifacts/mt-channel-broker.yaml
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/v2/context.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, lgtm

#1064 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1065 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, needs-ok-to-test

#1066 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#1063 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: needs-ok-to-test

#1078 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1079 [release-v1.17] Not just render oidc env-vars when cfg is on, we need also a present audience to ensure the camel containers work correct
  pkg/reconciler/integration/source/integrationsource.go
  pkg/reconciler/integration/source/integrationsource_test.go
Labels: approved, lgtm

#1109 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1113 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1072 [release-v1.15] Update Konflux configurations
  .tekton/kn-eventing-apiserver-receive-adapter-115-pull-request.yaml
  .tekton/kn-eventing-apiserver-receive-adapter-115-push.yaml
  .tekton/kn-eventing-appender-115-pull-request.yaml
  .tekton/kn-eventing-appender-115-push.yaml
  .tekton/kn-eventing-channel-controller-115-pull-request.yaml
  .tekton/kn-eventing-channel-controller-115-push.yaml
  .tekton/kn-eventing-channel-dispatcher-115-pull-request.yaml
  .tekton/kn-eventing-channel-dispatcher-115-push.yaml
  .tekton/kn-eventing-controller-115-pull-request.yaml
  .tekton/kn-eventing-controller-115-push.yaml
  .tekton/kn-eventing-event-display-115-pull-request.yaml
  .tekton/kn-eventing-event-display-115-push.yaml
  .tekton/kn-eventing-filter-115-pull-request.yaml
  .tekton/kn-eventing-filter-115-push.yaml
  .tekton/kn-eventing-heartbeats-115-pull-request.yaml
  .tekton/kn-eventing-heartbeats-115-push.yaml
  .tekton/kn-eventing-heartbeats-receiver-115-pull-request.yaml
  .tekton/kn-eventing-heartbeats-receiver-115-push.yaml
  .tekton/kn-eventing-ingress-115-pull-request.yaml
  .tekton/kn-eventing-ingress-115-push.yaml
  .tekton/kn-eventing-jobsink-115-pull-request.yaml
  .tekton/kn-eventing-jobsink-115-push.yaml
  .tekton/kn-eventing-migrate-115-pull-request.yaml
  .tekton/kn-eventing-migrate-115-push.yaml
  .tekton/kn-eventing-mtchannel-broker-115-pull-request.yaml
  .tekton/kn-eventing-mtchannel-broker-115-push.yaml
  .tekton/kn-eventing-mtping-115-pull-request.yaml
  .tekton/kn-eventing-mtping-115-push.yaml
  .tekton/kn-eventing-pong-115-pull-request.yaml
  .tekton/kn-eventing-pong-115-push.yaml
  .tekton/kn-eventing-schema-115-pull-request.yaml
  .tekton/kn-eventing-schema-115-push.yaml
  .tekton/kn-eventing-test-event-sender-115-pull-request.yaml
  .tekton/kn-eventing-test-event-sender-115-push.yaml
  .tekton/kn-eventing-test-eventshub-115-pull-request.yaml
  .tekton/kn-eventing-test-eventshub-115-push.yaml
  .tekton/kn-eventing-test-print-115-pull-request.yaml
  .tekton/kn-eventing-test-print-115-push.yaml
  .tekton/kn-eventing-test-recordevents-115-pull-request.yaml
  .tekton/kn-eventing-test-recordevents-115-push.yaml
  .tekton/kn-eventing-test-request-sender-115-pull-request.yaml
  .tekton/kn-eventing-test-request-sender-115-push.yaml
  .tekton/kn-eventing-test-wathola-fetcher-115-pull-request.yaml
  .tekton/kn-eventing-test-wathola-fetcher-115-push.yaml
  .tekton/kn-eventing-test-wathola-forwarder-115-pull-request.yaml
  .tekton/kn-eventing-test-wathola-forwarder-115-push.yaml
  .tekton/kn-eventing-test-wathola-receiver-115-pull-request.yaml
  .tekton/kn-eventing-test-wathola-receiver-115-push.yaml
  .tekton/kn-eventing-test-wathola-sender-115-pull-request.yaml
  .tekton/kn-eventing-test-wathola-sender-115-push.yaml
  .tekton/kn-eventing-webhook-115-pull-request.yaml
  .tekton/kn-eventing-webhook-115-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1115 [release-v1.16] Update Konflux configurations
  renovate.json
Labels: needs-ok-to-test

#1114 [release-v1.15] Update Konflux configurations
  renovate.json
Labels: needs-ok-to-test

#1116 [release-v1.17] Update Konflux configurations
  renovate.json
Labels: needs-ok-to-test

#1150 [main] Update dependabot configurations
  renovate.json
Labels: approved, lgtm, needs-ok-to-test

#1158 [release-v1.15] Update Konflux configurations
  rpms.lock.yaml
Labels: needs-ok-to-test

#1159 [release-v1.16] Update Konflux configurations
  rpms.lock.yaml
Labels: needs-ok-to-test

#1160 [release-v1.17] Update Konflux configurations
  rpms.lock.yaml
Labels: needs-ok-to-test

#1154 [release-v1.16] SinkBinding: Set specific conditions for reconciler steps
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/apis/sources/v1/sinkbinding_types.go
  pkg/reconciler/sinkbinding/sinkbinding.go
Labels: approved
