Repository openshift-knative/eventing, pull requests merged in 2025-03, with the labels that each got.

#1168 Bump OCP version to 4.19 for builder image
  openshift/generate.sh
Labels: approved, lgtm

#1171 [release-v1.16] Update Konflux configurations
  .tekton/kn-eventing-apiserver-receive-adapter-116-pull-request.yaml
  .tekton/kn-eventing-apiserver-receive-adapter-116-push.yaml
  .tekton/kn-eventing-appender-116-pull-request.yaml
  .tekton/kn-eventing-appender-116-push.yaml
  .tekton/kn-eventing-channel-controller-116-pull-request.yaml
  .tekton/kn-eventing-channel-controller-116-push.yaml
  .tekton/kn-eventing-channel-dispatcher-116-pull-request.yaml
  .tekton/kn-eventing-channel-dispatcher-116-push.yaml
  .tekton/kn-eventing-controller-116-pull-request.yaml
  .tekton/kn-eventing-controller-116-push.yaml
  .tekton/kn-eventing-event-display-116-pull-request.yaml
  .tekton/kn-eventing-event-display-116-push.yaml
  .tekton/kn-eventing-filter-116-pull-request.yaml
  .tekton/kn-eventing-filter-116-push.yaml
  .tekton/kn-eventing-heartbeats-116-pull-request.yaml
  .tekton/kn-eventing-heartbeats-116-push.yaml
  .tekton/kn-eventing-heartbeats-receiver-116-pull-request.yaml
  .tekton/kn-eventing-heartbeats-receiver-116-push.yaml
  .tekton/kn-eventing-ingress-116-pull-request.yaml
  .tekton/kn-eventing-ingress-116-push.yaml
  .tekton/kn-eventing-jobsink-116-pull-request.yaml
  .tekton/kn-eventing-jobsink-116-push.yaml
  .tekton/kn-eventing-migrate-116-pull-request.yaml
  .tekton/kn-eventing-migrate-116-push.yaml
  .tekton/kn-eventing-mtchannel-broker-116-pull-request.yaml
  .tekton/kn-eventing-mtchannel-broker-116-push.yaml
  .tekton/kn-eventing-mtping-116-pull-request.yaml
  .tekton/kn-eventing-mtping-116-push.yaml
  .tekton/kn-eventing-pong-116-pull-request.yaml
  .tekton/kn-eventing-pong-116-push.yaml
  .tekton/kn-eventing-schema-116-pull-request.yaml
  .tekton/kn-eventing-schema-116-push.yaml
  .tekton/kn-eventing-test-event-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-event-sender-116-push.yaml
  .tekton/kn-eventing-test-eventshub-116-pull-request.yaml
  .tekton/kn-eventing-test-eventshub-116-push.yaml
  .tekton/kn-eventing-test-print-116-pull-request.yaml
  .tekton/kn-eventing-test-print-116-push.yaml
  .tekton/kn-eventing-test-recordevents-116-pull-request.yaml
  .tekton/kn-eventing-test-recordevents-116-push.yaml
  .tekton/kn-eventing-test-request-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-request-sender-116-push.yaml
  .tekton/kn-eventing-test-wathola-fetcher-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-fetcher-116-push.yaml
  .tekton/kn-eventing-test-wathola-forwarder-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-forwarder-116-push.yaml
  .tekton/kn-eventing-test-wathola-receiver-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-receiver-116-push.yaml
  .tekton/kn-eventing-test-wathola-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-sender-116-push.yaml
  .tekton/kn-eventing-webhook-116-pull-request.yaml
  .tekton/kn-eventing-webhook-116-push.yaml
Labels: approved, lgtm, ok-to-test

#1172 [release-v1.17] Update Konflux configurations
  .tekton/kn-eventing-apiserver-receive-adapter-117-pull-request.yaml
  .tekton/kn-eventing-apiserver-receive-adapter-117-push.yaml
  .tekton/kn-eventing-appender-117-pull-request.yaml
  .tekton/kn-eventing-appender-117-push.yaml
  .tekton/kn-eventing-channel-controller-117-pull-request.yaml
  .tekton/kn-eventing-channel-controller-117-push.yaml
  .tekton/kn-eventing-channel-dispatcher-117-pull-request.yaml
  .tekton/kn-eventing-channel-dispatcher-117-push.yaml
  .tekton/kn-eventing-controller-117-pull-request.yaml
  .tekton/kn-eventing-controller-117-push.yaml
  .tekton/kn-eventing-event-display-117-pull-request.yaml
  .tekton/kn-eventing-event-display-117-push.yaml
  .tekton/kn-eventing-filter-117-pull-request.yaml
  .tekton/kn-eventing-filter-117-push.yaml
  .tekton/kn-eventing-heartbeats-117-pull-request.yaml
  .tekton/kn-eventing-heartbeats-117-push.yaml
  .tekton/kn-eventing-heartbeats-receiver-117-pull-request.yaml
  .tekton/kn-eventing-heartbeats-receiver-117-push.yaml
  .tekton/kn-eventing-ingress-117-pull-request.yaml
  .tekton/kn-eventing-ingress-117-push.yaml
  .tekton/kn-eventing-jobsink-117-pull-request.yaml
  .tekton/kn-eventing-jobsink-117-push.yaml
  .tekton/kn-eventing-migrate-117-pull-request.yaml
  .tekton/kn-eventing-migrate-117-push.yaml
  .tekton/kn-eventing-mtchannel-broker-117-pull-request.yaml
  .tekton/kn-eventing-mtchannel-broker-117-push.yaml
  .tekton/kn-eventing-mtping-117-pull-request.yaml
  .tekton/kn-eventing-mtping-117-push.yaml
  .tekton/kn-eventing-pong-117-pull-request.yaml
  .tekton/kn-eventing-pong-117-push.yaml
  .tekton/kn-eventing-schema-117-pull-request.yaml
  .tekton/kn-eventing-schema-117-push.yaml
  .tekton/kn-eventing-test-event-sender-117-pull-request.yaml
  .tekton/kn-eventing-test-event-sender-117-push.yaml
  .tekton/kn-eventing-test-eventshub-117-pull-request.yaml
  .tekton/kn-eventing-test-eventshub-117-push.yaml
  .tekton/kn-eventing-test-print-117-pull-request.yaml
  .tekton/kn-eventing-test-print-117-push.yaml
  .tekton/kn-eventing-test-recordevents-117-pull-request.yaml
  .tekton/kn-eventing-test-recordevents-117-push.yaml
  .tekton/kn-eventing-test-request-sender-117-pull-request.yaml
  .tekton/kn-eventing-test-request-sender-117-push.yaml
  .tekton/kn-eventing-test-wathola-fetcher-117-pull-request.yaml
  .tekton/kn-eventing-test-wathola-fetcher-117-push.yaml
  .tekton/kn-eventing-test-wathola-forwarder-117-pull-request.yaml
  .tekton/kn-eventing-test-wathola-forwarder-117-push.yaml
  .tekton/kn-eventing-test-wathola-receiver-117-pull-request.yaml
  .tekton/kn-eventing-test-wathola-receiver-117-push.yaml
  .tekton/kn-eventing-test-wathola-sender-117-pull-request.yaml
  .tekton/kn-eventing-test-wathola-sender-117-push.yaml
  .tekton/kn-eventing-webhook-117-pull-request.yaml
  .tekton/kn-eventing-webhook-117-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#1173 Use default builder image in dockerfile generator
  openshift/generate.sh
Labels: approved, lgtm

#1177 [release-v1.16] Bump to golang 1.23
  go.mod
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
  openshift/ci-operator/knative-images/appender/Dockerfile
  openshift/ci-operator/knative-images/channel_controller/Dockerfile
  openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
  openshift/ci-operator/knative-images/controller/Dockerfile
  openshift/ci-operator/knative-images/event_display/Dockerfile
  openshift/ci-operator/knative-images/filter/Dockerfile
  openshift/ci-operator/knative-images/heartbeats/Dockerfile
  openshift/ci-operator/knative-images/heartbeats_receiver/Dockerfile
  openshift/ci-operator/knative-images/ingress/Dockerfile
  openshift/ci-operator/knative-images/jobsink/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-images/mqttsource/Dockerfile
  openshift/ci-operator/knative-images/mtchannel_broker/Dockerfile
  openshift/ci-operator/knative-images/mtping/Dockerfile
  openshift/ci-operator/knative-images/pong/Dockerfile
  openshift/ci-operator/knative-images/schema/Dockerfile
  openshift/ci-operator/knative-images/webhook/Dockerfile
  openshift/ci-operator/knative-images/websocketsource/Dockerfile
  openshift/ci-operator/knative-test-images/event-sender/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/ci-operator/knative-test-images/print/Dockerfile
  openshift/ci-operator/knative-test-images/recordevents/Dockerfile
  openshift/ci-operator/knative-test-images/request-sender/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
  openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
  openshift/generate.sh
Labels: approved

#1182 [release-v1.17] Update Konflux configurations
  rpms.lock.yaml
Labels: needs-ok-to-test

#1201 Adding patch to remove upstream CM for Transformer/Integration images
  openshift/release/generate-release.sh
Labels: approved, lgtm

#1202 [release-v1.16] Fix camel env vars for sinks
  pkg/apis/common/integration/v1alpha1/aws.go
  pkg/reconciler/integration/helper.go
  pkg/reconciler/integration/helper_test.go
Labels: approved, lgtm

#1206 [release-v1.16] Update Konflux configurations
  .tekton/docker-build.yaml
  rpms.lock.yaml
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
Labels: approved, lgtm

#1211 [release-v1.16] Catch-up with upstream
  pkg/apis/sinks/v1alpha1/integration_sink_lifecycle.go
  pkg/reconciler/integration/sink/integrationsink.go
  pkg/reconciler/integration/sink/integrationsink_test.go
Labels: approved, lgtm

#1220 [release-v1.17] More integration sink backports to ocp
  pkg/apis/common/integration/v1alpha1/aws.go
  pkg/apis/sinks/v1alpha1/integration_sink_lifecycle.go
  pkg/reconciler/integration/helper.go
  pkg/reconciler/integration/helper_test.go
  pkg/reconciler/integration/sink/integrationsink.go
Labels: approved, lgtm
