Repository openshift-knative/eventing, pull requests merged in 2025-01, with the labels that each got.

#989 [release-v1.15] Register eventshub image for JobSink
  test/rekt/resources/jobsink/jobsink.go
Labels: approved

#993 [release-v1.15] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#994 [release-v1.16] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#996 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, needs-ok-to-test

#990 [release-v1.16] Register eventshub image for JobSink
  test/rekt/resources/jobsink/jobsink.go
Labels: approved, lgtm

#974 [release-v1.16] MT-Broker: return retriable status code based on the state to leverage retries
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
Labels: approved, lgtm

#1000 Allow skipping generate-release in experimtal tests
  openshift/e2e-common.sh
Labels: approved, lgtm

#1001 Fix seccompProfile patch
  openshift/patches/remove_seccompProfile.patch
Labels: approved, lgtm

#1005 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .tekton/kn-eventing-apiserver-receive-adapter-116-pull-request.yaml
  .tekton/kn-eventing-apiserver-receive-adapter-116-push.yaml
  .tekton/kn-eventing-appender-116-pull-request.yaml
  .tekton/kn-eventing-appender-116-push.yaml
  .tekton/kn-eventing-channel-controller-116-pull-request.yaml
  .tekton/kn-eventing-channel-controller-116-push.yaml
  .tekton/kn-eventing-channel-dispatcher-116-pull-request.yaml
  .tekton/kn-eventing-channel-dispatcher-116-push.yaml
  .tekton/kn-eventing-controller-116-pull-request.yaml
  .tekton/kn-eventing-controller-116-push.yaml
  .tekton/kn-eventing-event-display-116-pull-request.yaml
  .tekton/kn-eventing-event-display-116-push.yaml
  .tekton/kn-eventing-filter-116-pull-request.yaml
  .tekton/kn-eventing-filter-116-push.yaml
  .tekton/kn-eventing-heartbeats-116-pull-request.yaml
  .tekton/kn-eventing-heartbeats-116-push.yaml
  .tekton/kn-eventing-heartbeats-receiver-116-pull-request.yaml
  .tekton/kn-eventing-heartbeats-receiver-116-push.yaml
  .tekton/kn-eventing-ingress-116-pull-request.yaml
  .tekton/kn-eventing-ingress-116-push.yaml
  .tekton/kn-eventing-jobsink-116-pull-request.yaml
  .tekton/kn-eventing-jobsink-116-push.yaml
  .tekton/kn-eventing-migrate-116-pull-request.yaml
  .tekton/kn-eventing-migrate-116-push.yaml
  .tekton/kn-eventing-mtchannel-broker-116-pull-request.yaml
  .tekton/kn-eventing-mtchannel-broker-116-push.yaml
  .tekton/kn-eventing-mtping-116-pull-request.yaml
  .tekton/kn-eventing-mtping-116-push.yaml
  .tekton/kn-eventing-pong-116-pull-request.yaml
  .tekton/kn-eventing-pong-116-push.yaml
  .tekton/kn-eventing-schema-116-pull-request.yaml
  .tekton/kn-eventing-schema-116-push.yaml
  .tekton/kn-eventing-test-event-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-event-sender-116-push.yaml
  .tekton/kn-eventing-test-eventshub-116-pull-request.yaml
  .tekton/kn-eventing-test-eventshub-116-push.yaml
  .tekton/kn-eventing-test-print-116-pull-request.yaml
  .tekton/kn-eventing-test-print-116-push.yaml
  .tekton/kn-eventing-test-recordevents-116-pull-request.yaml
  .tekton/kn-eventing-test-recordevents-116-push.yaml
  .tekton/kn-eventing-test-request-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-request-sender-116-push.yaml
  .tekton/kn-eventing-test-wathola-fetcher-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-fetcher-116-push.yaml
  .tekton/kn-eventing-test-wathola-forwarder-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-forwarder-116-push.yaml
  .tekton/kn-eventing-test-wathola-receiver-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-receiver-116-push.yaml
  .tekton/kn-eventing-test-wathola-sender-116-pull-request.yaml
  .tekton/kn-eventing-test-wathola-sender-116-push.yaml
  .tekton/kn-eventing-webhook-116-pull-request.yaml
  .tekton/kn-eventing-webhook-116-push.yaml
Labels: needs-ok-to-test

#1009 [release-v1.15] JobSink with Istio config for Job spec
  test/rekt/features/jobsink/jobsink.go
  test/rekt/resources/jobsink/jobsink.go
Labels: approved, lgtm

#992 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: needs-ok-to-test

#1002 [release-v1.15] Reduce mt-broker-controller memory usage with namespaced endpoint informer (#8418)
  pkg/reconciler/broker/controller.go
Labels: approved

#1013 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#1035 [release-v1.15] Update Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#1037 [release-v1.16] Add sinks.knative.dev to namespaced ClusterRole
  config/core/roles/clusterrole-namespaced.yaml
  openshift/release/artifacts/eventing-core.yaml
Labels: approved, lgtm
