Repository openshift-knative/eventing, pull requests merged in 2025-08, with the labels that each got.

#1492 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: approved, lgtm

#1500 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#1449 [release-v1.18] Adding addressable duck on crd && run make generate release
  config/core/resources/eventtransform.yaml
  openshift/release/artifacts/eventing-core.yaml
  openshift/release/artifacts/eventing-crds.yaml
Labels: approved, lgtm

#1540 [release-v1.15] Update OWNERS file
  OWNERS
Labels: approved, lgtm

#1543 [release-v1.18] Update OWNERS file
  OWNERS
Labels: approved, lgtm

#1544 [release-v1.19] Update OWNERS file
  OWNERS
Labels: approved, lgtm

#1557 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, kind/sync-fork-to-upstream
